config/routes.rb
Rails.application.routes.draw do

  get 'search', to: "search#index"

  root :to => 'pages#home'

  resources :pages, only: :index do
    :recipes
  end

  resources :likes, only: [:create, :destroy]

  resources :users
  resources :recipes do
    resources :comments, only: [:new, :edit, :create, :update]

  end
  resources :comments
  
  # for session login
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :recipe, optional: true
    belongs_to :user, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  #-----only allows a user to like the post once-----
  validates :user_id, uniqueness: { scope: :recipe_id }

  # might need to add optional true for after deleting a user
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

    belongs_to :user, optional: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    
    #-----recipe has to have name and image-----
    validates :image, presence: true
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :recipes, dependent: :destroy
    has_many :comments
    has_many :likes
    
    #-----user has to have unique password and email-----
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
    before_action :set_theme
    before_action :set_query
    
    #-----search functionality-----
    def set_query
        @q = Recipe.ransack(params[:q])
    end
    private

    #-----light/dark theme button------
    def set_theme
        if params[:theme].present?
            theme = params[:theme].to_sym
            # session[:theme] = theme
            cookies[:theme] = theme
            redirect_to(request.referrer || root_path)
        end
    end

    # -----creates session user-----
    def fetch_user
        @current_user = User.find_by id: session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present?
    end

    # -----backend to only allow buttons/url to work for set users-----
    # current user
    def check_for_login
        redirect_to login_path unless @current_user.present?
    end
    # admin
    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
    # recipe owner
    def check_for_owner_recipe
        @current_recipe = Recipe.find(params[:id])
        redirect_to recipe_path(params[:id]) unless (@current_user.present? && @current_user.username == @current_recipe.user.username || @current_user.admin?)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #-----new comment-----
  def new
    @recipe = Recipe.find params[:recipe_id]
    @comment = @recipe.comments.build
  end
  def create  
      comment = Comment.new
      comment.content = params[:comment][:content]
      comment.user_id = @current_user.id
      comment.recipe_id = params[:recipe_id]
      comment.save 
      redirect_to recipe_path(params[:recipe_id])
  end

  #------edit comment-----
  def edit
    @recipe = Recipe.find params[:recipe_id]
    @comment = Comment.find params[:id]
  end
  def update
    comment = Comment.find params[:id]
    comment.content = params[:comment][:content]
    comment.save 
    redirect_to comment.recipe
  end

  #-----delete comment------
  def destroy
    comment = Comment.find params[:id]
    comment.destroy
    redirect_back(fallback_location: '/')
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :recipe_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    #-----like-----
    def create
        @like = @current_user.likes.new(like_params)
        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end

        redirect_to @like.recipe
    end
    
    #-----unlike-----
    def destroy
        @like = @current_user.likes.find(params[:id])
        recipe = @like.recipe
        @like.destroy
        redirect_to recipe
    end

    private
    def like_params
        params.require(:like).permit(:recipe_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #-----shows a random recipe on the home page-----
  def home
    @recipe = Recipe.order('RANDOM()').first
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :check_for_owner_recipe, only: [:edit, :update, :destroy]
  #-----show recipes-----
  def index
    @recipes = Recipe.all
  end
  def show
    @recipe = Recipe.find params[:id]
    ingredients = @recipe.ingredients
    #-----splits ingredients sentence into array for use in show view page can cause issues if other chars are used couldnt find an easy fix other then just removing it so make sure ingredients are seperated by comma-----
    @ingredients_as_arr = ingredients.split(', ', -1)
    @comment = Comment.all
  end

  #-----create recipe-----
  def new
    check_for_login
    @recipe = Recipe.new
  end
  def create
    @current_user.recipes.create recipe_params
    redirect_to recipes_path
  end

  #-----edit recipe-----
  def edit
    @recipe = Recipe.find params[:id]
  end
  def update
    recipe = Recipe.find params[:id]
    recipe.update recipe_params
    redirect_to recipe
  end

  #-----delete recipe-----
  def destroy
    recipe = Recipe.find params[:id]
    recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :instructions, :image, :category, :region)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  #-----ransack gem controller also used in application controller-----
  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  #-----creating new session-----
  def new
  end
  def create
    user = User.find_by username: params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end
  #-----ending session/logging out-----
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, only: [:index]

  #-----users display-----
  def index
    @users = User.all
  end
  def show
    @user = User.find params[:id]
    
  end

  #-----create new user-----
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  #-----edit user this is where u can add user picture and description (utilizes cloudinary)-----
  def edit
    @user = User.find params[:id]
  end
  def update
    user = User.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image = req["public_id"]
    end
    user.update user_params
    user.save
    redirect_to user
  end

  #-----delete user-----
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<h3>please be polite.</h3>

<%= form_for [@recipe, @comment] do |f| %>
    <%= f.text_area :content, placeholder: 'comment goes here', class: "about-input-field" %>
    <%= f.submit 'Submit', class: 'btn' %>
<% end %>

app/views/comments/new.html.erb
<h1>Write comment here</h1>

<h3>please be polite.</h3>

<%= form_for [@recipe, @comment] do |f| %>
    <%= f.text_area :content, placeholder: 'comment goes here', class: "about-input-field" %>
    <%= f.submit 'Submit', class: 'btn' %>
<% end %>

app/views/recipes/_form.html.erb
<div class="form-content">
    <%= form_for @recipe do |r| %>
        <%= r.text_field :name, placeholder: 'Recipe Name' %>
        <%= r.text_area :ingredients, placeholder: "Recipe Ingredients seperated by ,", class: "about-input-field" %>
        <%= r.text_area :instructions, placeholder: 'Meal description for homepage and cooking instructions', class: "about-input-field"  %>
        <%= r.url_field :image, placeholder: 'Image url link (must link to an already hosted image)' %>
        <%= r.text_field :category, placeholder: 'Meal category ie- Breakfast' %>
        <%= r.text_field :region, placeholder: 'Meal origin ie- Mexican' %>

        <%=r.submit 'Submit', class: 'btn' %>
    <% end %>
    <br>
</div>

app/views/recipes/edit.html.erb
<h1><%= @recipe.name %></h1>

<%= render 'recipes/form' %>

app/views/recipes/index.html.erb
<h1>All recipes</h1>
<%# sorted recipes with most recent at the top and displays all in a list %>
<% @recipes.order(:created_at).reverse_order.each do |r| %>
    <div class="recipe-content">
        <div class="grid-left">
            <div class="recipe-header">
                <h3><%= link_to r.name, r, class: 'btn' %></h3>
                <h3 class="recipe-owner">Created by: <%= link_to r.user.username, user_path(r.user), class: 'btn' %></h3>
            </div>
            <p class="desc-content"><%= r.instructions %> </p>
        </div>
        <div class="right">
            <img src="<%=r.image%>" alt="<%=r.name%>" class="index-img">
            <p class="timestamp recipe-timestamp"><%= r.created_at.strftime '%I:%M %p %A, %B %e, %Y' %></p>
        </div>
    </div>
<% end %>

app/views/recipes/new.html.erb
<h1>Create New Recipe</h1>

<%= render 'recipes/form' %>

app/views/recipes/show.html.erb
<div class="show-content">
    <br>
    <div class="secondary-nav">
        <h1><%= @recipe.name %></h1>
        <div class="buttons">
            <%= link_to @recipe.user.username, @recipe.user, class: 'btn' if @recipe.user != @current_user %>
            <%# if logged in and own account or an admin display edit and delete recipe buttons %>
            <% if @current_user.present? %>
                <% if @current_user == @recipe.user || @current_user.admin? %>
                    <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn"%>
                    <%= link_to 'Delete', @recipe, :method => 'delete', data: {confirm: 'are you sure you wish to delete recipe?'}, class: "btn"%>
                <% end %>
            <% end %>
        </div>
    </div>
    <img src="<%= @recipe.image %>" alt="<%= @recipe.name %>" class="img-show">
    <div class="likes-container">
        <%# google font icon classes and span for thumbs up %>
        <h2 class="likes-counter"><span class="material-icons-outlined thumb">thumb_up </span></h2><h2 class="counter-number"> <%= @recipe.likes.count %></h2>
        <%# like button functionality %>
        <% if @current_user.present? %>
        <% like = @current_user.likes.find_by(recipe: @recipe) %>
            <% if like.nil? %>
                <%= button_to 'Like', likes_path, params: { like: { recipe_id: @recipe.id }}, class: 'btn', method: :post %>
            <% else %>
                <%= button_to 'Unlike', like_path(like), class: 'btn', method: :delete %>
            <% end %>
        <% end %>
    </div>
    <div class="lower-grid">
        <div class="lower-left">
            <h3>Ingredients:</h3>
            <ul class="recipe-list">
                <%# converts ingredients array to dot points %>
                <% @ingredients_as_arr.each do |i| %>
                    <li><%= i %></li>
                <% end %>
            </ul>
        </div>
        <div class="lower-right">
            <h3>About:</h3>
            <p class="recipe-instructions"><%= @recipe.instructions %></p>
        </div>
    </div>
    <%# if logged in show comment button %>
    <% if @current_user.present? %>
        <%= link_to 'Add Comment', new_recipe_comment_path(@recipe), class: 'btn' %>
    <% end %>
    <br>
    <div class="comment-container">
        <% @comment.order(:created_at).reverse_order.each do |c| %>
                <% if c.recipe.id == @recipe.id %>
                    <div class="comment">
                        <div class="comment-header">
                            <h3><%= c.user.username %></h3>
                            <% if @current_user.present? %>
                                <%# if you made comment show edit and delete buttons TODO admin delete %>
                                <% if @current_user.id == c.user.id %>
                                    <div class="buttons-container">
                                        <%= link_to 'Edit', edit_recipe_comment_path(@recipe.id, c.id), class: "btn" %>
                                        <%= link_to 'Delete', c, method: 'delete', class: "btn" %>
                                    </div>
                                <% end %>
                            <% end %>
                        </div>
                        <p><%= c.content %></p>
                        <p class="timestamp comment-timestamp"><%= c.created_at.strftime '%I:%M %p %A, %B %e, %Y' %></p>
                    </div>
                    <br>
            <% end %>
        <% end %>
    </div>
</div>

app/views/search/_form.html.erb
<%= search_form_for(@q, url: search_path, method: :get) do |f| %>

    <%# these params allow different search functionality based on database tables or columns%>
    <%= f.search_field :name_or_instructions_or_user_username_or_region_or_category_i_cont_any, placeholder: "Search...", class: 'search-bar' %>
    <%= f.submit "Search!", class: "btn" %>
<% end %>

app/views/search/index.html.erb
<div class="show-content">
<div class="search">
    <h2>Search <%= pluralize(@recipes.count, "Result") %></h2>
    <%= render 'search/form' %>
</div>
<br>
<%# for displaying all search results no algo to how they are sorted %>
<% @recipes.each do |r| %>
    <div class="recipe-content">
        <div class="grid-left">
            <div class="recipe-header">
                <h3><%= link_to r.name, r, class: 'btn' %></h3>
                <h3 class="recipe-owner">Created by: <%= link_to r.user.username, user_path(r.user), class: 'btn' %></h3>
            </div>
            <p class="desc-content"><%= r.instructions %> </p>
        </div>
        <img src="<%=r.image%>" alt="<%=r.name%>" class="index-img">
    </div>
<% end %>
</div>

app/views/session/new.html.erb
<h1>Login</h1>

<div class="login-form">
    <%= form_tag login_path do %>
    <%= text_field_tag :username, nil, placeholder: 'Username' %>
    <%= password_field_tag :password, nil, placeholder: 'Password' %>
    <%= submit_tag 'login', class: 'btn' %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Complete Your Profile</h1>

<%= form_for(@user, html: {multipart: true}) do |f| %>
    <%= f.label :image %>
    <%= f.cl_image_upload :image %>
    <%= f.label :about %>
    <%= f.text_area :about, class: "about-input-field" %>
    <%= f.submit 'Complete Profile', class: 'btn' %>
<% end %>

app/views/users/index.html.erb
<h1>ADMIN page</h1>

<%# very basic functionality for displaying users that have created accounts %>
<% @users.each do |user| %>
    <p><%= user.username %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
    <ol>
        <% @users.errors.full_messages.each do |msg| %>
            <li>>%= msg %></li>
        <% end %>
    </ol>
<% end %>

<%= form_for @user do |f| %>
    <%= f.text_field :username, placeholder: 'Username' %>
    <%= f.email_field :email, placeholder: 'Example@email.com' %>
    <%= f.password_field :password, placeholder: 'Password' %>
    <%= f.password_field :password_confirmation, placeholder: 'Password confirmation' %>

    <%= f.submit 'Sign up!', class: 'btn' %>
<% end %>

app/views/users/show.html.erb
<%# this subheading only shows for when you are logged in and on your profile page this allows you to change some settings ect %>
<% if @current_user.present? %>
    <% if @current_user == @user %>
        <div class="owner-nav nav-btns">
            <%# light dark theme using cookies for memory %>
            <% if cookies[:theme] == "light" %>
                <%= link_to "Dark", root_path(theme: "dark"), class: 'btn' %>
            <% else %>
                <%= link_to "Light", root_path(theme: "light"), class: 'btn' %>
            <% end %>
            <%# gives access to admin page if you are admin %>
            <% if @current_user.admin? %>
                <%= link_to 'Admin', users_path, class: 'btn'  %>
            <% end %>
            <%= link_to 'Edit', edit_user_path(@user), class: 'btn sesions btns' %>
            <%= link_to 'Delete', @user, method: 'delete', data: {confirm: 'are you sure you wish to leave us?'}, class: 'btn session-btns' %>
        <% end %>
    </div>
<% end %>


<div class="profile-grid">
    <div class="grid-left">
        <div class="profile-header">
            <h1><%= @user.username %></h1>
            <p class="timestamp">Member since: <%= @user.created_at.strftime '%m, %Y' %></p>
        </div>
        <p class="user-bio"><%= @user.about %></p>
    </div>
    <div class="grid-right">
        <%= cl_image_tag @user.image, class: 'profile-image' if @user.image.present? %>
    </div>
    <br>
    <div class="user-recipes">
        <%# displays recipes most recent at top %>
        <% @user.recipes.order(:created_at).reverse_order.each do |r| %>
            <div class="recipe-content">
                <div class="grid-left">
                    <div class="recipe-header">
                        <h3 class="recipe-name"><%= link_to r.name, r, class: 'btn' %></h3>
                    </div>
                    <p class="desc-content"><%= r.instructions %> </p>
                </div>
                <div class="right">
                    <img src="<%=r.image%>" alt="<%=r.name%>" class="index-img">
                    <p class="timestamp recipe-timestamp"><%= r.created_at.strftime '%I:%M %p %A, %B %e, %Y' %></p>
                </div>
            </div>
        <% end %>
    </div>
</div>