config/routes.rb
Rails.application.routes.draw do

  get 'search', to: "search#index"

  root :to => 'pages#home'

  resources :pages, only: :index do
    :recipes
  end

  resources :likes, only: [:create, :destroy]

  resources :users
  resources :recipes do
    resources :comments, only: [:new, :edit, :create, :update]

  end
  resources :comments
  
  # for session login
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :recipe, optional: true
    belongs_to :user, optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  #-----only allows a user to like the post once-----
  validates :user_id, uniqueness: { scope: :recipe_id }

  # might need to add optional true for after deleting a user
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

    belongs_to :user, optional: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    
    #-----recipe has to have name and image-----
    validates :image, presence: true
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :recipes, dependent: :destroy
    has_many :comments
    has_many :likes
    
    #-----user has to have unique password and email-----
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #-----new comment-----
  def new
    @recipe = Recipe.find params[:recipe_id]
    @comment = @recipe.comments.build
  end
  def create  
      comment = Comment.new
      comment.content = params[:comment][:content]
      comment.user_id = @current_user.id
      comment.recipe_id = params[:recipe_id]
      comment.save 
      redirect_to recipe_path(params[:recipe_id])
  end

  #------edit comment-----
  def edit
    @recipe = Recipe.find params[:recipe_id]
    @comment = Comment.find params[:id]
  end
  def update
    comment = Comment.find params[:id]
    comment.content = params[:comment][:content]
    comment.save 
    redirect_to comment.recipe
  end

  #-----delete comment------
  def destroy
    comment = Comment.find params[:id]
    comment.destroy
    redirect_back(fallback_location: '/')
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :recipe_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    #-----like-----
    def create
        @like = @current_user.likes.new(like_params)
        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end

        redirect_to @like.recipe
    end
    
    #-----unlike-----
    def destroy
        @like = @current_user.likes.find(params[:id])
        recipe = @like.recipe
        @like.destroy
        redirect_to recipe
    end

    private
    def like_params
        params.require(:like).permit(:recipe_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #-----shows a random recipe on the home page-----
  def home
    @recipe = Recipe.order('RANDOM()').first
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :check_for_owner_recipe, only: [:edit, :update, :destroy]
  #-----show recipes-----
  def index
    @recipes = Recipe.all
  end
  def show
    @recipe = Recipe.find params[:id]
    ingredients = @recipe.ingredients
    #-----splits ingredients sentence into array for use in show view page can cause issues if other chars are used couldnt find an easy fix other then just removing it so make sure ingredients are seperated by comma-----
    @ingredients_as_arr = ingredients.split(', ', -1)
    @comment = Comment.all
  end

  #-----create recipe-----
  def new
    check_for_login
    @recipe = Recipe.new
  end
  def create
    @current_user.recipes.create recipe_params
    redirect_to recipes_path
  end

  #-----edit recipe-----
  def edit
    @recipe = Recipe.find params[:id]
  end
  def update
    recipe = Recipe.find params[:id]
    recipe.update recipe_params
    redirect_to recipe
  end

  #-----delete recipe-----
  def destroy
    recipe = Recipe.find params[:id]
    recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :instructions, :image, :category, :region)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  #-----ransack gem controller also used in application controller-----
  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  #-----creating new session-----
  def new
  end
  def create
    user = User.find_by username: params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end
  #-----ending session/logging out-----
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, only: [:index]

  #-----users display-----
  def index
    @users = User.all
  end
  def show
    @user = User.find params[:id]
    
  end

  #-----create new user-----
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  #-----edit user this is where u can add user picture and description (utilizes cloudinary)-----
  def edit
    @user = User.find params[:id]
  end
  def update
    user = User.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image = req["public_id"]
    end
    user.update user_params
    user.save
    redirect_to user
  end

  #-----delete user-----
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anek+Odia&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= cloudinary_js_config %>
  </head>
<%# cookies theme saves theme preference to browser for next use %>
  <body class="<%= cookies[:theme] %>">
    <div class="navigation">
      <div class="nav-btns">
        <%= link_to 'COOKBOOK', root_path, class: 'btn' %>
        <%= link_to 'All Recipes', recipes_path, class: 'btn' %>
        <%# only allows new recipes to be made by people with accounts %>
        <% if @current_user.present? %>
          <%= link_to 'New Recipe', new_recipe_path, class: 'btn' %>
        <% end %>
      </div>
      <div class="session-btns">
        <%# only access to account settings and sign out if you are logged in %>
        <% if @current_user.present? %>
          <%= link_to @current_user.username, @current_user, class: 'btn' %>
          <%= link_to 'Sign out', login_path, method: 'delete', class: 'btn'  %>
        <% else %>
          <%# only shows if logged out %>
          <%= link_to 'Login', login_path, class: 'btn'  %>
          <%= link_to 'Sign up', new_user_path, class: 'btn'  %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="show-content">
    <div class="search">
        <h1>COOKBOOK</h1>
        <%= render 'search/form' %>
    </div>
    <br>
    <div class="feature">
        <%= link_to recipe_path(@recipe) do %>
            <%= image_tag @recipe.image, class: 'homepage-img'%>
        <% end %>
    </div>
</div>